### Propiedades de las matrices: multiplicación asociativa, distributiva, pero no conmutativa.

In [2]:
import numpy as np

In [4]:
A = np.array([[2,3], [5,7], [11,13]])
B = np.array([[1,3], [2,1]])
C = np.array([[3,1], [4,2]])

In [5]:
A.dot(B.dot(C)) == A.dot(B).dot(C)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [6]:
A.dot(B + C) == A.dot(B) + A.dot(C)

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [7]:
B.dot(C) == C.dot(B)

array([[False, False],
       [False, False]])

### La multiplicación de vectores SÍ es conmutativa:

In [8]:
v1 = np.array([[2], [7]])
v2 = np.array([[3], [5]])

In [9]:
(v1.T).dot(v2) == (v2.T).dot(v1)

array([[ True]])