In [1]:
import numpy as np

### Se plantea el sistema de ecuaciones:
#### 3x + y = 1
#### 2x + y = 1

### Y se lo expresa en forma matricial:

In [6]:
A = np.array([[3,1], [2,1]])
print(A)

[[3 1]
 [2 1]]


In [7]:
b = np.array([1,1])
print(b)

[1 1]


In [8]:
np.set_printoptions(suppress = True)
# seteamos numpy de tal manera que si tenemos un num muy cercano a 0, lo aproxime a 0 directamente.

#### Calculo la inversa de A:

In [10]:
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 1. -1.]
 [-2.  3.]]


#### Y ahora a partir de ella, como vimos en la clase anterior, nuestro x:
#### x = A⁻¹.b

In [13]:
x = inversa_A.dot(b)
print(x)

[0. 1.]


### Verificamos la solución

In [14]:
A.dot(x) == b

array([ True,  True])