In [1]:
import numpy as np

In [3]:
v = np.array([1,2,3,4,5])

matrix = np.diag(v)

print(matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### No tienen porque ser cuadradas.

In [5]:
print(matrix[0:4, 0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [6]:
print(matrix[0:3, 0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


### Estas dos últimas también son cuadradas.

In [7]:
A = np.diag([2,3,4,5])
A

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [8]:
v1 = np.array([1,1,1,1])
v1

array([1, 1, 1, 1])

In [9]:
A.dot(v1.T)

array([2, 3, 4, 5])

### La inversa de una matriz diagonal es fácil de calcular: es otra matriz con la inversa de cada uno de sus elementos.

In [11]:
A_inv = np.diag([1/2, 1/3, 1/4, 1/5])
A_inv

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

In [12]:
A.dot(A_inv)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Chequeado.

### Ahora lo chequeamos computacionalmente:

In [13]:
np.linalg.inv(A)

array([[0.5       , 0.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.2       ]])

### Hecho.

### Ahora: matrices simétricas (cuando A = A_transpuesta)

### Las matrices diagonales siempre son simétricas.

In [15]:
sim = np.array([[1,  2, 3 ],
                [2, -1, 7 ],
                [3,  7, 11]])

In [16]:
sim == sim.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])