### Una matriz es ortogonal si sus filas son ortogonales entre sí, y sus columnas también (entre sí).

In [15]:
import numpy as np

In [16]:
matrix = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1]])

In [17]:
col1 = matrix[:,0]
col1

array([1, 0, 0])

In [18]:
col2 = matrix[:,1]

In [19]:
col1.dot(col2)

0

### Las columnas 1 y 2 son ortogonales.

In [20]:
col3 = matrix[:,2]

In [21]:
col1.dot(col3)

0

In [22]:
col2.dot(col3)

0

### El resto de las columnas también son ortogonales entre sí, entonces el conjunto de las columnas es ortogonal.

In [25]:
fila1 = matrix[0,:]
fila2 = matrix[1,:]
fila3 = matrix[2,:]

print(fila1.dot(fila2))
print(fila1.dot(fila3))
print(fila2.dot(fila3))

0
0
0


### El conjunto de las filas también son ortogonales entre sí.

### Con esto, concluímos que la matriz es ortogonal.

### En las matrices ortogonales:
#### A.A_T = A_T.A = Id  <==>  A_T = A⁻¹

In [26]:
A = np.array([[np.cos(100), -np.sin(100)],
              [np.sin(100),  np.cos(100)]])

In [27]:
A

array([[ 0.86231887,  0.50636564],
       [-0.50636564,  0.86231887]])

In [29]:
print(np.linalg.norm(A[0,:]))
print(np.linalg.norm(A[1,:]))
print(np.linalg.norm(A[:,0]))
print(np.linalg.norm(A[:,1]))

0.9999999999999999
0.9999999999999999
0.9999999999999999
0.9999999999999999


In [30]:
print(A[0,:].dot(A[1,:])) # el prod interno de una fila con la otra.
print(A[:,0].dot(A[:,1])) # el prod interno entre columnas.

0.0
0.0


### Es una matriz ortogonal con sus filas y columnas de norma 1 (dato extra).

In [31]:
A_T = A.T
print(A_T.dot(A))
print(A.dot(A_T))

[[ 1.00000000e+00 -7.93771519e-18]
 [-7.93771519e-18  1.00000000e+00]]
[[1.00000000e+00 7.93771519e-18]
 [7.93771519e-18 1.00000000e+00]]


### Son matrices iguales (A.A_T = A_T.A), además el resultado es la matriz identidad.
### Esto último no se puede ver en el resultado debido al error al manejar floats.

### Se arregla con la siguiente línea.

In [32]:
np.set_printoptions(suppress=True)

### Ahora podemos ver que el resultado es el correcto.

In [33]:
A_T = A.T
print(A_T.dot(A))
print(A.dot(A_T))

[[ 1. -0.]
 [-0.  1.]]
[[1. 0.]
 [0. 1.]]
