In [1]:
import numpy as np

In [14]:
escalar = 5.679

vector = np.array([1,2,3,4])

matriz = np.array([[1,2,3,4], [2,4,6,8], [4,8,12,16]])

tensor = np.array([
    [[255,0,0,10],   [0,255,0,10],     [0,0,255,10]],
    [[255,255,0,10], [0,255,255,10],   [255,0,255,10]],
    [[0,0,0,10],     [128,128,128,10], [255,255,255,10]]
])

In [4]:
escalar.T
# no existe transponer un escalar.

AttributeError: 'float' object has no attribute 'T'

In [7]:
vector.T
# no se ven cambios a menos que se hagan cuentas

array([1, 2, 3, 4])

In [9]:
matriz.T

array([[ 1,  2,  4],
       [ 2,  4,  8],
       [ 3,  6, 12],
       [ 4,  8, 16]])

In [12]:
matriz.T.shape

(4, 3)

In [15]:
tensor.T

array([[[255, 255,   0],
        [  0,   0, 128],
        [  0, 255, 255]],

       [[  0, 255,   0],
        [255, 255, 128],
        [  0,   0, 255]],

       [[  0,   0,   0],
        [  0, 255, 128],
        [255, 255, 255]],

       [[ 10,  10,  10],
        [ 10,  10,  10],
        [ 10,  10,  10]]])

In [16]:
matriz == matriz.T.T

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### Suma de matrices:

In [17]:
m1 = np.array([[1,7], [4,-3]])
m2 = np.array([[-2,5], [4,6]])
m1 + m2

array([[-1, 12],
       [ 8,  3]])

In [18]:
matriz + escalar
# suma a cada valor de la matriz el escalar

array([[ 6.679,  7.679,  8.679,  9.679],
       [ 7.679,  9.679, 11.679, 13.679],
       [ 9.679, 13.679, 17.679, 21.679]])