In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([2,3])
matriz = np.array([[1,2], [3,4], [5,6]])

In [9]:
print(vector)

[2 3]


In [10]:
print(matriz)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
A = matriz * vector
# aca hace broadcasting, extiende el vector a tres filas iguales.

In [5]:
B = matriz.dot(vector)
# esta es la multiplicacion de matrices algebraica (matriz x vector_T)
# en este caso, funciona sin transponer al vector por funcionamiento de python

In [7]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [8]:
print(B)

[ 8 18 28]


In [13]:
matriz @ vector
# otra opcion para hacer producto interno.

array([ 8, 18, 28])

In [14]:
vector @ matriz

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

#### Podemos ver que se respetan las reglas de dimensiones de los elementos de algebra.

In [16]:
vector.T @ matriz

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)