In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
B = np.array([[2,3], [5,7], [11,13]])

In [10]:
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
print(B)

[[ 2  3]
 [ 5  7]
 [11 13]]


In [3]:
print(A.shape)

(4, 3)


In [5]:
print(B.shape)

(3, 2)


In [6]:
A.dot(B)

array([[ 45,  56],
       [ 99, 125],
       [153, 194],
       [207, 263]])

In [7]:
B.dot(A)

ValueError: shapes (3,2) and (4,3) not aligned: 2 (dim 1) != 4 (dim 0)